function Main()

    InicializoTablas()
    /* CreoClientes()
    CreoFormasdePago()
    AsignoFPagoaClientes()
    MuestroClientesyformasdepago()
    CreoFacturas()
    ObtengoFacturaCompleta()
    Estadoylogdelmodelo()
    EstadodeCambios()
    CreoMasclientes()
    Buscosinindice()
    PrimeroUltimo()
    ModificoClientes()
    ModificacionMasiva()
    BorradoDeRegistros()
    MetodosConsulta() 
    PruebaLazyLoad()
    Validaciones()
    Paginacion()*/
    Relaciones()

Return ( Nil )

Function PathOfFile( oTORMModel )
Return  ( '.\' )