function Main()

    InicializoTablas()
    CreoClientes()
    CreoFormasdePago()
    AsignoFPagoaClientes()
    MuestroClientesyformasdepago()
    CreoFacturas()
    ObtengoFacturaCompleta()
    ForeignKey()
    //Estadoylogdelmodelo()
    //EstadodeCambios()
    //CreoMasclientes()
    //Buscosinindice()
    //PrimeroUltimo()
    //ModificoClientes()
    //ModificacionMasiva()
    //BorradoDeRegistros()
    //MetodosConsulta() 
    //PruebaLazyLoad()
    //Validaciones()
    //Paginacion()
    //Relaciones()

Return ( Nil )

Function PathOfFile( oTORMModel )
Return  ( '.\db\' )